### ISSUE TITLE
Doesn't Seem to work on OPX

### ISSUE THREAD

**Issue by bfayers** [Magisk-Modules-Repo/magisk-wifi-bonding#1]
Device: OneplusX (onyx)
Software: Latest LineageOS
Mods: OpenGapps, Magisk
What doesn't happen: Still only uses link speed: 72Mbps, router is set wireless mode "Up to 200Mbps"

**Comment by bfayers** [comment]
If anymore details are required let me know.

**Comment by simonsmh** [comment]
It seems that 801 is just out of date. I can't find related Information on Internet. Sorry for that.

**Comment by bfayers** [comment]
@simonsmh from what i can see apaprently the 801 chipset doesn't support 40MHz. Shame really, oh well.
