### ISSUE TITLE
Does nothing on OnePlus5

### ISSUE THREAD

**Issue by TheGoblinHero** [Magisk-Modules-Repo/magisk-wifi-bonding#2]
On OP5 default WCNSS_qcom_cfg.ini has only "gChannelBondingMode5GHz=1" parameter. So sed replacement does not work and 2.4 bonding is not activated. Your module should check first if "gChannelBondingModeXXXGHz" exists and add this parameter otherwise.

**Comment by simonsmh** [comment]
Does op5 enabled this 2.4 bonding by default?

**Comment by TheGoblinHero** [comment]
No, it's disabled by default. Adding "gChannelBondingMode24GHz=1" manually really increase the wi-fi speed.

**Comment by simonsmh** [comment]
Let me know if 1.1 works for you.

**Comment by TheGoblinHero** [comment]
It works now, thx!
